# Generated by Django 4.2.7 on 2025-10-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='action_items',
            field=models.JSONField(blank=True, default=list, help_text='AI-extracted action items from the meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='key_points',
            field=models.JSONField(blank=True, default=list, help_text='AI-identified key discussion points'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_url',
            field=models.URLField(blank=True, help_text='URL to the meeting recording', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='transcript',
            field=models.TextField(blank=True, help_text='AI-generated transcript of the meeting'),
        ),
    ]
